{% set build = 0 %}
{% set version = '3.7.4' %}
{% set sha256 = '2fb782844e3bc265a8d181c3c3e2632a4ca073111c874c654f1365d33ca2eb8a' %}
# TODO:
# wait for decision on mpi metapackage, then we can set values for supported mpi
# implementations in conda-forge.yml
{% set mpi = os.environ.get('MPI') or 'mpich' %}

package:
  name: slepc
  version: {{version}}

source:
  fn:  slepc-{{version}}.tar.gz
  url: http://slepc.upv.es/download/distrib/slepc-{{version}}.tar.gz
  sha256: {{sha256}}

build:
  number: {{build}}
  binary_relocation: true
  detect_binary_files_with_prefix: true
  skip: true  # [win]

requirements:
  build:
    - python 2.*
    - {{mpi}}
    - petsc {{version[:3]}}*
  run:
    - {{mpi}}
    - petsc {{version[:3]}}*

test:
  requires:
    - pkg-config
  commands:
    - PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig pkg-config --cflags SLEPc

about:
  home: http://slepc.upv.es/
  summary: 'SLEPc: Scalable Library for Eigenvalue Problem Computations'
  license: LGPL 3
  license_file: COPYING.LESSER

extra:
  recipe-maintainers:
    - dalcinl
    - minrk
